feat: Add awesome_bot as a GitHub Action
reHackable/awesome-reMarkable pull request #195
Opened 2024-01-02 16:05 UTC by robsliwi

Solves https://github.com/reHackable/awesome-reMarkable/issues/190

2024-01-02 18:45 UTC, robsliwi commented
Just for sake of completeness here a CI run: https://github.com/robsliwi/awesome-reMarkable/actions/runs/7389317762/job/20101886841?pr=1

It reveals that https://github.com/reHackable/awesome-reMarkable/blob/master/README.md?plain=1#L132 is reporting a 404 as it's missing a character in the end.

https://github.com/robsliwi/awesome-reMarkable/pull/1/commits/06024d98dd3d8eaa971ea3eee1329c53ab24641d fixes the broken link and introduces the newly green CI :green_heart:

2024-01-02 19:06 UTC, Eeems requested changes
Just some minor nitpicks. Thank you for tackling this!

2024-01-02 19:06 UTC, Eeems commented on .github/workflows/ci.yml
> +name: Ruby
This should probably be changed to something more meaningful, like `Verify links`

2024-01-02 19:06 UTC, Eeems commented on .github/workflows/ci.yml
> +    branches: [ '*' ]
We probably don't need to run this on PRs against any branch other than the main one.

2024-01-02 19:06 UTC, Eeems commented on .github/workflows/ci.yml
> +    branches: [ '*' ]
We probably don't need to run this on any branch other than the main one.

2024-01-02 19:06 UTC, Eeems commented on .github/workflows/ci.yml
> +  build:
We could probably rename this to `check` or something similar.

2024-01-03 19:28 UTC, Eeems approved these changes

2024-01-03 19:29 UTC, merged